site_name: BitterBuster Documentation
theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.integrate

extra_css:
  - css/style.css

nav:
  - Home: index.md
  - BitterBuster: 
    - Installation: bitterbuster/installation.md
    - Build: bitterbuster/build.md
    - Implementation Details: bitterbuster/implementation.md
    - User Guide [WIP]: bitterbuster/user_guide.md
    - Data Schema: 
      - Game Configuration: bitterbuster/data/config.md
      - Logging Data: bitterbuster/data/logging.md
      - AI Support [WIP]: bitterbuster/data/ai.md
  - Candy Generator: 
    - Documentation: candygenerator/docs.md
  - License: license.md
