site_name: BitterBuster Documentation
theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.integrate

extra_css:
  - css/style.css

nav:
  - Home: index.md
  - Developer:
    - BitterBuster: 
      - Installation: bitterbuster/installation.md
      - Build: bitterbuster/build.md
      - Implementation Details: bitterbuster/implementation.md
    - Candy Generator: candy_generator.md
    - Data Schema: 
      - Game Configuration: data_config.md
      - Logging Data: data_logging.md
      - AI Support: data_ai.md
  - User:
    - BitterBuster Gameplay Guide: user_guide.md
  - License: license.md
